---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  # name: techtalksdb-data
  name: {{ .Values.name | quote }}
  
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  # - ReadWriteOnce
    - {{ .Values.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.capacity | quote }}